"""FastAPI dependencies."""

from src.infrastructure.web.dependencies.injection import (
	get_conversation_repository,
	get_conversation_use_case,
	get_authenticate_user_use_case,
	get_create_user_use_case,
	get_current_user,
	get_current_admin_user,
	get_db,
	get_list_user_conversations_use_case,
	get_list_all_conversations_use_case,
	get_list_user_requests_use_case,
	get_optional_user,
	get_request_repository,
	get_request_use_case,
	get_send_message_use_case,
	get_submit_request_use_case,
	get_user_repository,
	get_user_use_case,
	# Service dependencies
	get_service_category_repository,
	get_service_vendor_repository,
	get_vendor_image_repository,
	get_list_categories_use_case,
	get_create_category_use_case,
	get_update_category_use_case,
	get_list_vendors_by_category_use_case,
	get_vendor_detail_use_case,
	get_create_booking_use_case,
	get_list_user_bookings_use_case,
	get_create_vendor_use_case,
	get_update_vendor_use_case,
	get_delete_vendor_use_case,
	get_add_vendor_image_use_case,
	get_delete_vendor_image_use_case,
	get_reorder_vendor_images_use_case,
	get_vendor_image_use_case,
)

__all__ = [
	"get_db",
	"get_current_user",
	"get_current_admin_user",
	"get_optional_user",
	"get_user_repository",
	"get_create_user_use_case",
	"get_authenticate_user_use_case",
	"get_user_use_case",
	"get_request_repository",
	"get_conversation_repository",
	"get_submit_request_use_case",
	"get_request_use_case",
	"get_list_user_requests_use_case",
	"get_conversation_use_case",
	"get_send_message_use_case",
	"get_list_user_conversations_use_case",
	"get_list_all_conversations_use_case",

	# Service exports
	"get_service_category_repository",
	"get_service_vendor_repository",
	"get_vendor_image_repository",
	"get_list_categories_use_case",
	"get_list_vendors_by_category_use_case",
	"get_create_category_use_case",
	"get_update_category_use_case",
	"get_vendor_detail_use_case",
	"get_create_vendor_use_case",
	"get_update_vendor_use_case",
	"get_delete_vendor_use_case",
	"get_add_vendor_image_use_case",
	"get_delete_vendor_image_use_case",
	"get_reorder_vendor_images_use_case",
	"get_vendor_image_use_case",
]
